spring:
  profiles: db
  datasource:
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    platform: postgres
    url: jdbc:postgresql://localhost:5432/nova
    username: root
    password: root
  jpa:
    generate:
      ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        ddl-auto: none
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect

server:
  port: ${PORT:8080}
  address: 0.0.0.0 # Bind all

graphql:
  servlet:
    enabled: true
    corsEnabled: true
    mapping: /graphql
